site_name:
    "Bootstrapping Your Transition from Streamlit OSS to Streamlit in Snowflake
    (SiS)"
site_url: https://snowflake-labs.github.io/streamlit-oss-to-sis-bootstrap/
site_description:
    Bootstrap your transition from Streamlit OSS to Streamlit in Snowflake (SiS)
    with this step-by-step tutorial and starter template. Migrate your Streamlit
    app to Snowflake's powerful and scalable platform, and leverage
    enterprise-grade features with ease.
extra_css:
    - stylesheets/extra.css
theme:
    name: material
    palette:
        primary: white
    logo: assets/snowflake-logo-blue.svg
    favicon: assets/favicon.ico
    font: false
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.footer
        - toc.follow
nav:
    - "Overview": index.md
    - "Environment Setup": setup.md
    - "Deploy to Streamlit Cloud": deploy_to_streamlit_cloud.md
    - "Penguins App":
          - "Exploring Dataset": explore_dataset.md
          - "Interact with Application": interactive_features.md
          - "Data Preparation": data_preparation.md
          - "Training and Prediction": train_and_predict.md
    - "Streamlit in  Snowflake":
          - "Deploy to Snowflake": snowflake_deploy.md
    - "Summary": "summary.md"
markdown_extensions:
    - toc:
          baselevel: 1
          permalink: "&para;"
    - admonition
    - attr_list
    - def_list
    - footnotes
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
          use_pygments: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins: []
# plugins:
#     - search
#     - table-reader

