site_name: "Streamlit 101: From Open Source to Snowflake Native Development"
site_url: https://snowflake-labs.github.io/zero-to-streamlit/
site_description: Getting started with Streamlit OSS and Streamlit in Snowflake.
extra_css:
    - stylesheets/extra.css
theme:
    name: material
    palette:
        primary: custom

    font:
        text: Roboto
        code: Fira Code
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.footer
        - toc.follow
nav:
    - "Overview": index.md
    - "Environment Setup": setup.md
    - "Deploy to Streamlit Cloud": deploy_to_streamlit_cloud.md
    - "Penguins App":
          - "Exploring Dataset": datset.md
          - "Interact with Application": interactivity.md
          - "Data Prepration": data_prepration.md
          - "Training and Prediction": train_and_predict.md
    - "Streamlit in  Snowflake":
          - "Deploy to Snowflake": snowflake_deploy.md
    - "Summary": "summary.md"
markdown_extensions:
    - toc:
          baselevel: 1
          permalink: "&para;"
    - admonition
    - attr_list
    - footnotes
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins: []
# plugins:
#     - search
#     - table-reader

